services:
  php:
    build:
      context: ./docker/php
    volumes:
      - '.:/var/www/html'

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - '.:/var/www/html'
      - './docker/nginx/conf.d:/etc/nginx/conf.d'

  mysql:
    image: mysql:8
    hostname: 8092a0bbc26b
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - './docker/volume/mysql:/var/lib/mysql'